### ISSUE TITLE
Lighthouse CLI args are not the same as config flags

### ISSUE THREAD

**Issue by DavidReinberger** [andreasonny83/lighthouse-ci#21]
Hey everyone, as i mentioned at the PR#19 I can't properly pass some flags to lighthouse simply because the CLI has different arguments than the programmatic approach eg. cli has an option
`--presets` but programmatic does not have this option and uses something called `onlyCategories` or `onlyAudits`, which is an array of strings.

~~This can be achieved with an external config mentioned [here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md#usage), it's probably a good idea to mention this in the docs.~~

Edit: after some investigation the CLI flag for the config file is ignored

**Comment by andreasonny83** [comment]
Hi @DavidReinberger . Can you please add some steps to reproduce the bug so I can reproduce the problem and run some investigations? 
Thanks again for the feedback

**Comment by PhilippSpo** [comment]
The issue is that when using `lighthouse` from node programmatically the `configPath` option is ignored and ["needs to be passed as the 3rd argument to lighthouse"](https://github.com/GoogleChrome/lighthouse/blob/v4.3.1/docs/readme.md#differences-from-cli-flags).

The config argument however is never passed:
https://github.com/andreasonny83/lighthouse-ci/blob/2e2bf4fc9667dbd6b15944b03750d08cdb1af8a4/lib/lighthouse-reporter.js#L54-L58

To support this we would basically need to read the file that is provided at `config-path` and pass it here programmatically.

**Comment by andreasonny83** [comment]
Thanks @PhilippSpo .
I'll try to have a look at this issue during the weekend.
However, if you are able to raise a PR I would be more than happy to review that and release a new version of the package.

**Comment by andreasonny83** [comment]
@DavidReinberger @PhilippSpo ,
I release with the custom-config support as part as [lighthouse-ci v1.7.0](https://github.com/andreasonny83/lighthouse-ci/releases/tag/v1.7.0).
Looking forward to hearing your feedback.

Thanks for your help.

**Comment by PhilippSpo** [comment]
@andreasonny83 Thanks! Works like a charm 👏 🏆
