### ISSUE TITLE
LHError: CRI_TIMEOUT

### ISSUE THREAD

**Issue by Koen028** [andreasonny83/lighthouse-ci#39]
I'm currently getting the following error when running `lighthouse-ci`.
## Error:
```
- Running Lighthouse on <THIS IS THE STAGING URL> ...

LHError: CRI_TIMEOUT
ERROR: Job failed: command terminated with exit code 1
```
## Command:
```
lighthouse-ci $STAGING_URL --score=$LIGHTHOUSE_SCORE --report=./ --filename=lighthouse.html
```
Any idea what's going on here?
I'm running it on the docker image [browserless/chrome](https://hub.docker.com/r/browserless/chrome)

**Comment by andreasonny83** [comment]
Thanks for reporting that @Koen028 .
I've never seen that error before but I'll try to run some investigations based on your report.
I can try to mention @asmagin, just to see if he may have any clue on that.

**Comment by andreasonny83** [comment]
Also @Koen028 , can you please confirm if the error appears even when running lighthouse-ci outside of that Docker image?

**Comment by asmagin** [comment]
@Koen028 @andreasonny83 haven't seen this either. 

This is the only place where such error is referenced: [here](https://nuget.pkg.github.com/GoogleChrome/lighthouse/blob/41879adb31aab2bca2a06b74826dbf84ea0be28a/lighthouse-core/lib/lh-error.js#L39)

**Comment by andreasonny83** [comment]
I suppose the error may be related to the `$STAGING_URL` being under some firewall rules or vpn restrictions hence not accessible from lighthouse direcly (just an assumption of course).
So I'm going to close this issue for now since I haven't heard any other feedback from @Koen028 and nobody else reported similar behaviour.
Feel free to repoen this issue if the problem is not resolved
