### ISSUE TITLE
v1.10.3 failed

### ISSUE THREAD

**Issue by Broutard** [andreasonny83/lighthouse-ci#73]
Since I update to 1.10.3, it failed

```
- Running Lighthouse on https://www.google.com ...

TypeError: Found non-callable @@iterator
```

**Comment by ChildishGiant** [comment]
Yep, no clue how to use this

**Comment by marcschaller** [comment]
This has been fixed in the pull request https://github.com/andreasonny83/lighthouse-ci/pull/71, as soon as @andreasonny83 merges it we should be good to go.
Furthermore, there is another pull request (still in draft, waiting for the previous one merge) https://github.com/andreasonny83/lighthouse-ci/pull/72 that adds a test to prevent any future broken release.

**Comment by andreasonny83** [comment]
Thanks for the fix @marcschaller and apologize for any inconvenience

**Comment by marcschaller** [comment]
(credits go to @Remi-p as well 😄 )

**Comment by andreasonny83** [comment]
I'll release 1.10.4 in a minute
